desihub/LSS

bin/mkCat_tar4ang.py
py/LSS/imaging/select_samples.py

Not finished/complete, but working well enough and I don't want to leave it hanging while developing other things

Testimaging

---

bin/gatherSV_zinfo_alltiles.py
py/LSS/zcomp/zinfo.py

adds TARGETS (tile type), EXPS (string, comma separated for exposures used), and {B,R,Z}_DEPTH_EBVAIR columns

Zcat addcolumns

---

py/LSS/SV3/altmtltools.py
py/LSS/SV3/fatools.py

First version of code to generate and track alternate MTL history. Also added changes to fatools which creates output directory if it doesn't exist, and sources the desi environment script within the bash shell script output by get_fba_fromnewmtl.

First version of Alternate MTL code + Minor changes to fatools

---

bin/mpi_bitweights
py/LSS/bitweights.py

Basically I just added the additional arguments for the output filename and "overwrite" option for the output fits file.
I have tested that the modification works.

add additional arguments to mpi_bitweights and bitweights.py

---

bin/mpi_bitweights

Modify a little bit on the instruction for setting the number of nodes and ntasks-per-node to run the code.
The old one is a bit confusing.

modify the instruction for running the code

---

py/LSS/ssr_tools.py

--Fix get_qso_data_full to allow you to load true quasars that redrock thinks are stars (SPECTYPE==STAR)
--Add code that allows you to split the quasar samples by galactic latitude and make comparative plots

Allow loading QSOs with SPECTYPE STAR, and split qsos by galactic latitude

---

scripts/main/apply_blinding_main.py

just a modification of apply_blinding_main.py to change the order of two pieces of code

modification of apply_blinding_main.py

---

py/LSS/mocktools.py
scripts/mock_tools/mkCat_mock.py

made changes to mocktools and mkCat_mock.py to make mock density equal data

modified mock code to equal density with data

---

scripts/xirunpc.py

Added an argument to xirunpc.py for filtering by absolute magnitude.

Added magnitude limit arguments

---

scripts/mock_tools/prepare_mocks_main.py

Replaced the current "mockver" argument which relies exclusively on the AbacusSummit mocks being the only mocks in use with a pair of arguments "mockpath" and "mockfile" which completely specify the base directories and (formattable) file names for the individual mocks. 
I maintained the function of the mockver for the single case of "ab_firstgen" as a legacy option but the current default options (which set mockver to None) manages to find the files as before and this option will likely be removed in the future. 
The only major difference for people wanting to use the default options (mockpath/mockfile) as though it were the legacy option (mockver) is that they would need to specify the full output directory under base_output rather than relying on the code to append …

changes to make prepare_mock_main more generic

---

py/LSS/imaging/sky_maps.py

Modify read_sky_maps to allow for the option of running with only one input random file

Adm pix sys

---

scripts/main/apply_blinding_main_fromfile_fcomp.py

Hi @ashleyjross , 
Here the updated code to add the fnl blinding scheme. 
You need now launch the python code via` srun -n 128 python main/apply_blinding_main_fromfile_fcomp.py`.
To apply the fnl blinding schme, you should use the flag --fnlblind 'y'. 
Edmond

Add fnl blinding

---

py/LSS/SV3/altmtltools.py

This should have made it into the last pull request but seems to have vanished from my code and stashed changes.... 
Nearly all of this pull request is the (re)addition of the ELG Priority shuffling feature, but there was also a bug with how a startDate of an empty string was handled, so that fix is in here as well.

restored ELG Priority Shuffling Feature

---

py/LSS/main/cattools.py
scripts/getpotaY1_mock.py

better accommodations for ez mocks

changes to cattools and getpota

---

scripts/validation/validation_sky.py

Jiaxi added a Healpix version for plotting the density map (Rongpu's function) with and without imaging systematics. This version has been used in preparing slides for the AAS243 DESI special session in 2024.

add healpix version (Rongpu's code) of density map

---

scripts/validation/validation_ssr_plot.py

the redshift success rate of all Y1 tracers on the focal plane without WEIGHT_ZFAIL. The map was not very different from that with WEIGHT_ZFAIL

full.dat.fits: plot SSR on the focal plane without ZFAIL. 

---

scripts/mock_tools/ffa2clus_fast.py

only change 'TARGETID' to 'TARGETID_DATA' once when generating randoms sequentially in ran_col_assign() function

mock_tools debug

---

py/LSS/qso_cat_utils.py

I add cuts for WISE VAR QSO that are SNCD targets. This is ~30 000 non DESI QSO targets that are classified as QSO. 
Does not impact the clustering catalog.

add cuts for WISE VAR QSO sncd target

---

scripts/validation/validation_ssr_plot.py

changed DECaLS to DECam; updated directory according to Y1 v1.3; corrected invalid directories

changed directory for Y1 v1.3

---

py/LSS/qso_cat_utils.py

Following the Christophe study using the VI table and the 1xdepth tiles with the new version of QN, I update the confidence level cut to keep the purity high as before to construct the QSO catalog. The new version of QN improves the completeness and the redshift efficiency.
Note: I wait the final Kibo run to update the cut for the bump in z~3.75, if it is still needed.

update CL cut for the new version of QN in Jura

---

scripts/validation/validation_ssr_plot.py

Modified the redshift success rate redshift ranges to match the clustering range. Tests done for jura-v1 and kibo-v1 ver0.1

redshift success rate that matches the clustering redshift range

---

py/LSS/qso_cat_utils.py

After discussion of the DESI data telecon of 17/09/2024.
Changes are only for DESI QSO targets for now.

update cuts for Kibo (QSO targets only)

---

py/LSS/SV3/altmtltools.py

Fixed issue where PromoteFraceELG variable did nothing and the promotion fraction was hardcoded to 10%. 
Also moved debug log statements in same function behind "if debug:"

Allow variable fraction of ELG targets to be promoted to ELG_HIP
